import asyncio
import json
from typing import Optional
from contextlib import AsyncExitStack
from mcp import ClientSession, StdioServerParameters
from src.backend.rag.env import deployment_name, client
from mcp.client.stdio import stdio_client
import os
from dotenv import load_dotenv

DEPLOYMENT_NAME = deployment_name
load_dotenv()

class MCPClient:
    """
    Client for interacting with an MCP server (e.g. jira_server.py).

    This class:
    - Establishes a connection to an MCP server over stdio
    - Retrieves available tools exposed by the server
    - Sends user queries to an LLM with tool-calling capabilities
    - Executes tool calls via the MCP server when requested by the LLM
    - Aggregates final responses into a single output string
    """
    def __init__(self):
        """
        Initialize the MCP client.

        Attributes:
            session (Optional[ClientSession]): Active MCP session used to communicate with the server
            exit_stack (AsyncExitStack): Manages async context cleanup (stdio + session)
            client: OpenAI/Azure client used for LLM responses
        """
        self.session: Optional[ClientSession] = None
        self.exit_stack = AsyncExitStack()
        self.client = client

    async def connect_to_server(self, server_module: str):
        """
        Connect to an mcp server via stdio and initialize a session.

        This method:
        - Launches the Mcp server as a subprocess using `python -m <server_module>`
        - establishes a stdio transport channel
        - creates a clientSesion for communication
        - initialises the session and retrieves available tools

        Args:
            server_module (str): Python module path to the MCP server
                                 (e.g. "rag_chatbot.mcp.servers.jira_server")
        """
        server_params = StdioServerParameters(
            command="python",
            args=["-m", server_module],
            env={**os.environ, "PYTHONPATH": "src"},
        )

        stdio_transport = await self.exit_stack.enter_async_context(stdio_client(server_params))
        self.stdio, self.write = stdio_transport

        # create mcp sesion over stdio
        self.session = await self.exit_stack.enter_async_context(ClientSession(self.stdio, self.write))

        await self.session.initialize()

        # List available tools
        response = await self.session.list_tools()
        tools = response.tools
        print("\nConnected to server with tools:", [tool.name for tool in tools])

    async def process_query(self, query: str) -> str:
        """
        Process a user query using an LLM with MCP tool-calling support.

        Workflow:
        1. Retrieve available MCP tools
        2. Send query + tool definitions to the LLM
        3. If LLM requests tool calls:
            - Execute tool via MCP server
            - Send results back to LLM
        4. Repeat until no more tool calls are made
        5. Return final aggregated text response

        Args:
            query (str): User input query

        Returns:
            str: Final response generated by the LLM after any tool usage
        """
        # asking MCP server what tools it has:
        tool_response = await self.session.list_tools()
        # convert to OpenAI format
        available_tools = [
            {
                "type": "function",
                "name": tool.name,
                "description": tool.description or "",
                "parameters": tool.inputSchema,
            }
            for tool in tool_response.tools
        ]

        final_text = []

        # model receives user message + List of available tools 
        response = self.client.responses.create(
            model=DEPLOYMENT_NAME,
            input=query, # query + history with query coming first
            tools=available_tools,
            max_output_tokens=5000,
        )

        # response of LLM will be the type (function_call) 
        # name and arguments of the tool(s) it wants to call #

        # loop allows the model to call mutliple tools
        while True:
            had_tool_call = False
            next_inputs = []

            for item in response.output:
                # message is just text the model responded with
                if item.type == "message":
                    for part in item.content:
                        if part.type == "output_text":
                            # extract the text an add it to final answer
                            final_text.append(part.text)

                # function called a tool
                elif item.type == "function_call":
                    had_tool_call = True
                    tool_name = item.name
                    tool_args = json.loads(item.arguments)
                    # format of item:
                    # {
                    # "name": "create_jira_issue",
                    # "arguments": {
                    #     "summary": "...",
                    #     "description": "..."
                    # }

                    # call MCP tool: create_jira_issue(summary, description)
                    result = await self.session.call_tool(tool_name, tool_args)

                    if hasattr(result, "content"):
                        #output from MCP tool called
                        tool_output = str(result.content) 
                    else:
                        tool_output = str(result)

                    next_inputs.append({
                        "type": "function_call_output",
                        "call_id": item.call_id,
                        "output": tool_output,
                    })

            # If a tool was called the loop starts again and sets has_tool_call to false again
            # so loop breaks when no more tools are left to call or no tools where ever called
            if not had_tool_call:
                break
            
            # the previous response ID allows the model to remember the user question,
            # tool call and tool result
            response = self.client.responses.create(
                model=DEPLOYMENT_NAME,
                previous_response_id=response.id,
                input=next_inputs,
                tools=available_tools,
                max_output_tokens=1000,
            )

        return "\n".join(final_text).strip()


    async def chat_loop(self):
        """Run an interactive chat loop"""
        print("\nMCP Client Started!")
        print("Type your queries or 'quit' to exit.")

        while True:
            try:
                query = input("\nQuery: ").strip()

                if query.lower() == 'quit':
                    break

                response = await self.process_query(query)
                print("\n" + response)

            except Exception as e:
                print(f"\nError: {str(e)}")

    async def cleanup(self):
        """Clean up resources"""
        await self.exit_stack.aclose()

async def main():    
    server_module = "src.backend.mcp.servers.jira_server"
    client = MCPClient()
    try:
        await client.connect_to_server(server_module)
        await client.chat_loop()
    finally:
        await client.cleanup()

if __name__ == "__main__":
    asyncio.run(main())